name: SkipNight
version: '1.0'
main: me.bebo.skipNight.SkipNight
# This tells the server the plugin is compatible with 1.16 and newer versions.
api-version: '1.16'
author: Bebo
description: A plugin that allows players to vote to skip the night.
commands:
  skipnight:
    description: Starts or participates in a vote to skip the night.
    usage: /skipnight [reload|stats]
    aliases: [sn]
  skipnightstats:
    description: Shows skip night voting statistics.
    usage: /skipnightstats
permissions:
  skipnight.vote:
    description: Allows players to vote to skip the night.
    default: true
  skipnight.stats:
    description: Allows viewing vote statistics.
    default: true
  skipnight.reload:
    description: Allows reloading the plugin's configuration.
    default: op