# The official name of your plugin.
name: SkipNight
# The main class that Spigot will load.
main: me.bebo.skipNight.SkipNight
# The version of your plugin. It's good practice to update this with new features.
version: '1.1'
# The Spigot API version this plugin is built against. 1.16 provides broad compatibility.
api-version: '1.16'
# Your name.
author: Bebo
# A more descriptive text for your plugin page.
description: A feature-rich plugin that allows players to vote to skip the night using a GUI, clickable messages, and more!

# Define all the commands your plugin uses.
commands:
  skipnight:
    description: Main command to vote, open the GUI, or manage the plugin.
    usage: "/skipnight [gui|reload|stats]"
    aliases: [sn, skip]
  skipnightstats:
    description: Shows global voting statistics.
    usage: "/skipnightstats"
    aliases: [snstats]

# Define all the permissions your plugin uses for easy management.
permissions:
  skipnight.*:
    description: Grants access to all SkipNight commands.
    children:
      - skipnight.vote
      - skipnight.gui
      - skipnight.stats
      - skipnight.reload
  skipnight.vote:
    description: Allows a player to vote to skip the night or start a vote.
    default: true
  skipnight.gui:
    description: Allows a player to open the vote status GUI.
    default: true
  skipnight.stats:
    description: Allows a player to view the voting statistics.
    default: true
  skipnight.reload:
    description: Allows a player to reload the plugin's configuration.
    default: op